import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./src/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} relative w-screen h-screen flex flex-col justify-start items-center `}
      >
        <Header />
        <main className="w-full h-full">{children}</main>
      </body>
    </html>
  );
}
